using Microsoft.EntityFrameworkCore;
using SeatFlow.Api;
using System.Text.Json.Serialization;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddDbContext<SeatFlowDb>(o => o.UseSqlite(builder.Configuration.GetConnectionString("SeatFlow") ?? "Data Source=seatflow.db"));
builder.Services.AddSingleton<MemoryNotificationService>(); builder.Services.AddSingleton<INotificationService>(sp => sp.GetRequiredService<MemoryNotificationService>()); builder.Services.AddScoped<RegistrationService>();
builder.Services.AddCors(o => o.AddDefaultPolicy(p => p.WithOrigins("http://localhost:5173").AllowAnyHeader().AllowAnyMethod()));
builder.Services.ConfigureHttpJsonOptions(o => o.SerializerOptions.Converters.Add(new JsonStringEnumConverter()));
var app = builder.Build(); app.UseCors();
using (var scope = app.Services.CreateScope()) { var db = scope.ServiceProvider.GetRequiredService<SeatFlowDb>(); await db.Database.EnsureCreatedAsync(); await Seed(db); }
app.MapGet("/api/workshops", async (SeatFlowDb db) => await db.Workshops.OrderBy(w => w.StartTime).Select(w => new { w.Id, w.Title, w.StartTime, w.EndTime, w.Capacity, ConfirmedCount = w.Registrations.Count(r => r.Status == RegistrationStatus.Confirmed), RemainingCapacity = w.Capacity - w.Registrations.Count(r => r.Status == RegistrationStatus.Confirmed) }).ToListAsync());
app.MapPost("/api/workshops", async (CreateWorkshop input, SeatFlowDb db) => { var error = ValidateWorkshop(input); if (error != null) return Results.BadRequest(new { error }); var w = new Workshop { Title = input.Title.Trim(), StartTime = input.StartTime, EndTime = input.EndTime, Capacity = input.Capacity }; db.Workshops.Add(w); await db.SaveChangesAsync(); return Results.Created($"/api/workshops/{w.Id}", w); });
app.MapGet("/api/participants", async (SeatFlowDb db) => await db.Participants.OrderBy(p => p.Name).ToListAsync());
app.MapGet("/api/workshops/{id:int}/registrations", async (int id, SeatFlowDb db) => { if (!await db.Workshops.AnyAsync(w => w.Id == id)) return Results.NotFound(); return Results.Ok(await db.Registrations.Where(r => r.WorkshopId == id).Include(r => r.Participant).OrderBy(r => r.CreatedAt).Select(r => new { r.Id, r.WorkshopId, r.ParticipantId, ParticipantName = r.Participant!.Name, ParticipantEmail = r.Participant.Email, r.Status, r.CreatedAt }).ToListAsync()); });
app.MapPost("/api/workshops/{id:int}/registrations", async (int id, CreateRegistration input, HttpRequest request, RegistrationService service) => { try { var r = await service.Register(id, input.ParticipantId, request.Headers["Idempotency-Key"].FirstOrDefault()); return Results.Ok(ToResponse(r)); } catch (KeyNotFoundException ex) { return Results.NotFound(new { error = ex.Message }); } catch (InvalidOperationException ex) { return Results.Conflict(new { error = ex.Message }); } catch (DbUpdateException ex) { return Results.Conflict(new { error = ex.InnerException?.Message ?? "Duplicate registration or idempotency key" }); } });
app.MapPost("/api/registrations/{id:int}/cancel", async (int id, RegistrationService service) => { try { return Results.Ok(ToResponse(await service.Cancel(id))); } catch (KeyNotFoundException ex) { return Results.NotFound(new { error = ex.Message }); } });
app.MapGet("/api/participants/{id:int}/schedule", async (int id, SeatFlowDb db) => { if (!await db.Participants.AnyAsync(p => p.Id == id)) return Results.NotFound(); return Results.Ok(await db.Registrations.Where(r => r.ParticipantId == id && r.Status == RegistrationStatus.Confirmed).Include(r => r.Workshop).OrderBy(r => r.Workshop!.StartTime).Select(r => new { r.Id, r.Status, WorkshopId = r.WorkshopId, Title = r.Workshop!.Title, StartTime = r.Workshop.StartTime, EndTime = r.Workshop.EndTime }).ToListAsync()); });
app.Run();
static string? ValidateWorkshop(CreateWorkshop w) => string.IsNullOrWhiteSpace(w.Title) || w.Title.Length > 160 ? "Title is required and must be at most 160 characters" : w.EndTime <= w.StartTime ? "End time must be after start time" : w.Capacity < 1 ? "Capacity must be at least 1" : null;
static object ToResponse(Registration r) => new { r.Id, r.WorkshopId, r.ParticipantId, r.Status, r.CreatedAt };
static async Task Seed(SeatFlowDb db) { if (await db.Workshops.AnyAsync()) return; var day = DateTime.UtcNow.Date.AddDays(7).AddHours(9); db.Workshops.AddRange(new Workshop { Title="Designing for Everyone", StartTime=day, EndTime=day.AddHours(2), Capacity=2 }, new Workshop { Title="Practical TypeScript", StartTime=day.AddHours(1), EndTime=day.AddHours(3), Capacity=3 }, new Workshop { Title="Product Discovery", StartTime=day.AddHours(3), EndTime=day.AddHours(5), Capacity=2 }, new Workshop { Title="Building Better APIs", StartTime=day.AddDays(1), EndTime=day.AddDays(1).AddHours(2), Capacity=3 }); db.Participants.AddRange(new Participant { Name="Alex Morgan", Email="alex@example.com" }, new Participant { Name="Sam Lee", Email="sam@example.com" }, new Participant { Name="Jordan Patel", Email="jordan@example.com" }, new Participant { Name="Taylor Kim", Email="taylor@example.com" }, new Participant { Name="Casey Smith", Email="casey@example.com" }); await db.SaveChangesAsync(); }
public sealed record CreateWorkshop(string Title, DateTime StartTime, DateTime EndTime, int Capacity);
public sealed record CreateRegistration(int ParticipantId);
public partial class Program { }
